### PR TITLE
Fix except statement. This was causing an error on import using python 3 on Ubuntu 20.04.

### PR DESCRIPTION
**Pull request by rolker**

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Thanks -- have you scanned to code for other issues with except?

This is very old code, and there were changes way back with how that was handled that may never have been fixed.

In the meantime, I'll merge this.

**Comment by rolker** [comment]
Thanks for quickly taking care of this. A quick scan did not reveal any other such issues and the module imported without error after this fix.

I realize this is very old code but I was reviving some of my own very old code that used this module so I was glad to find this repo!

**Comment by ChrisBarker-NOAA** [comment]
and this repo exists because some of my very old code is also using it :-)

And I need to update that code soon, so thanks!

**Comment by ChrisBarker-NOAA** [comment]
NOTE: I've incremented the version and pushed a new release as well.

**Pull request merged**
